---
- name: Deploy application to host
  hosts: n2
  become: yes
  vars:
    artifact_source: /var/lib/jenkins/workspace/Dev-team-30/myapp.zip
    deploy_path: /var/www/html

  tasks:
    - name: Copy artifact to target location
      copy:
        src: "{{ artifact_source }}"
        dest: "{{ deploy_path }}/myapp.zip"

    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present

    - name: Extract the artifact
      unarchive:
        src: "{{ deploy_path }}/myapp.zip"
        dest: "{{ deploy_path }}"
        remote_src: yes

    - name: Restart Apache
      service:
        name: apache2   # Change to 'httpd' if you're on RHEL/CentOS
        state: restarted

