- name: Install OpenJDK 17 on Ubuntu
  hosts: all
  become: yes

  vars:
    java_package: openjdk-17-jdk

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Java 17 (OpenJDK)
      apt:
        name: "{{ java_package }}"
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Show installed Java version
      debug:
        var: java_version.stdout

