- name: Ensure MySQL Python dependencies are installed on Ubuntu nodes
  hosts: webservers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL module
      apt:
        name: python3-pymysql
        state: present

