---
# Tasks to install MySQL

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server package
  apt:
    name: "{{ mysql_packages }}"
    state: present

- name: Ensure MySQL service is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

