- name: Import SQL into MySQL
  hosts: webservers
  become: yes
  vars:
    db_name: studentdb
    db_user: root
    db_password: password

  tasks:
    - name: Copy SQL file to remote host
      copy:
        src: files/init.sql
        dest: /tmp/init.sql

    - name: Import SQL into database
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /tmp/init.sql
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"

